# Generated by Django 2.2.5 on 2019-10-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='creation date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Delete date ')),
            ],
        ),
    ]
