# Generated by Django 2.2.5 on 2019-10-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='creation date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Delete date ')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category name')),
                ('image', models.ImageField(upload_to='category/', verbose_name='Category Image')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.DeleteModel(
            name='main',
        ),
    ]
