# Generated by Django 2.2.5 on 2019-10-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='creation date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Delete date ')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('web', models.URLField(blank=True, null=True, verbose_name='web')),
            ],
            options={
                'verbose_name': 'Social network',
                'verbose_name_plural': 'Social networks',
            },
        ),
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='creation date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Delete date ')),
                ('about_us', models.TextField(verbose_name='About us ')),
                ('phone', models.EmailField(max_length=20, verbose_name='phone ')),
                ('email', models.CharField(max_length=150, verbose_name='E-mail')),
                ('address', models.CharField(max_length=200, verbose_name='Adress ')),
            ],
            options={
                'verbose_name': 'Web',
                'verbose_name_plural': 'Webs',
            },
        ),
    ]
