# Generated by Django 2.2.5 on 2019-10-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_social_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='creation date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Delete date ')),
                ('firts_name', models.CharField(max_length=100, verbose_name='Firts name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('Email', models.EmailField(max_length=150, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contac',
                'verbose_name_plural': 'Contacs',
            },
        ),
        migrations.CreateModel(
            name='suscribers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='creation date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Delete date ')),
                ('Email', models.EmailField(max_length=150, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Suscriber',
                'verbose_name_plural': 'Suscribers',
            },
        ),
    ]
